Upgrade sass-rails
On upgrading rails 4.2.4, e fixed sass-rails' version because we got an error
NameError: uninitialized constant Sass::Script` on travis.
ref:
 https://github.com/rails/sass-rails/issues/315
 http://stackoverflow.com/questions/29716284/uninitialized-constant-sassscript-nameerror