Update god
I got a below errors with OSX10.8.5 and ruby 2.2.3 when starting
bin/yohoushi.

dyld: lazy symbol binding failed: Symbol not found: _rb_thread_select
  Referenced from:
  /Users/nikushi.nobuhiro/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/god-0.13.2/ext/god/kqueue_handler_ext.bundle
    Expected in: flat namespace

dyld: Symbol not found: _rb_thread_select
  Referenced from:
  /Users/nikushi.nobuhiro/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/god-0.13.2/ext/god/kqueue_handler_ext.bundle
    Expected in: flat namespace

God supports ruby 2.2.0 from god v0.13.5 so we must have updated it.
https://github.com/mojombo/god/commit/e8a2c2d490a6c5293e2175328c781f68e27408cf